name: Tests

on:
  - push

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --silent --ignore-scripts
      - name: Run tests
        run: yarn test
