name: Tests

on:
  - push
  - pull_request

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --silent --ignore-scripts
      - name: Run tests
        run: yarn test

  types:
    name: Type checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --silent --ignore-scripts
      - name: Check types
        run: yarn types

  format:
    name: Code formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --silent --ignore-scripts
      - name: Check formatting
        run: yarn check-format

  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --silent --ignore-scripts
      - name: Lint flipper plugin
        run: yarn workspace flipper-plugin-performance run lint

  build:
    name: Package builds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --silent --ignore-scripts
      - name: Build packages
        env:
          PACKAGES: flipper-plugin-performance react-native-performance
        run: for p in $PACKAGES; do pushd packages/$p && npm pack --dry-run && popd; done
